{
 "title": "🗺 Connections Map",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval Mins.", "query": "3,5,10,15,30,60" }
  ]
 },
 "panels": [
  { "title": "🗺 Connections Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Data Points Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  COUNT(*) AS count\r\nFROM \r\n  geodata\r\n"
    }
   ]
  },
  {
   "title": "Data Points By Period",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  COUNT(*) AS count\r\nFROM \r\n  geodata\r\nWHERE \r\n  $__timeFilter(created_at)\r\n"
    }
   ]
  },
  {
   "title": "Top 10 Most Active Cities",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  city,\r\n  COUNT(*) AS count\r\nFROM \r\n  geodata\r\nWHERE \r\n  $__timeFilter(created_at)\r\nGROUP BY \r\n  city\r\nORDER BY \r\n  count DESC\r\nLIMIT 10\r\n"
    }
   ]
  },
  {
   "title": "Unique Cities Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  COUNT(DISTINCT city) AS count\r\nFROM \r\n  geodata\r\n"
    }
   ]
  },
  {
   "title": "Unique Cities By Period",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  COUNT(DISTINCT city) AS count\r\nFROM \r\n  geodata\r\nWHERE \r\n  $__timeFilter(created_at)\r\n"
    }
   ]
  },
  {
   "type": "geomap",
   "gridPos": { "h": 20, "w": 10, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "WITH filtered_data AS (\r\n  SELECT *\r\n  FROM geodata\r\n  WHERE $__timeFilter(created_at)\r\n),\r\ntotal_count AS (\r\n  SELECT COUNT(*) AS cnt FROM filtered_data\r\n),\r\ngroup_counts AS (\r\n  SELECT \r\n    region,\r\n    region_name,\r\n    city,\r\n    zip,\r\n    isp,\r\n    org,\r\n    as_info,\r\n    COUNT(*) AS group_count\r\n  FROM filtered_data\r\n  GROUP BY region, region_name, city, zip, isp, org, as_info\r\n)\r\nSELECT\r\n  g.lat,\r\n  g.lon,\r\n  g.city,\r\n  g.isp,\r\n  g.org,\r\n  tc.cnt::float / gc.group_count AS weight\r\nFROM filtered_data g\r\nJOIN group_counts gc\r\n  ON g.region = gc.region\r\n  AND g.region_name = gc.region_name\r\n  AND g.city = gc.city\r\n  AND g.zip = gc.zip\r\n  AND g.isp = gc.isp\r\n  AND g.org = gc.org\r\n  AND g.as_info = gc.as_info\r\nCROSS JOIN total_count tc\r\n"
    }
   ]
  },
  {
   "title": "New Connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  date_trunc('minute', created_at) - INTERVAL '1 minute' * (EXTRACT(minute FROM created_at)::int % ${interval}) AS time,\r\n  COUNT(*) AS total\r\nFROM\r\n  geodata\r\nWHERE\r\n  $__timeFilter(created_at)\r\nGROUP BY\r\n  time\r\nORDER BY\r\n  time ASC\r\n"
    }
   ]
  }
 ]
}